version: "3.8"

services:
  # db-service:
  #   image: mysql:5.7.22
  #   container_name: "db-service"
  #   restart: always
  #   environment: 
  #     MYSQL_DATABASE: admin
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: root
  #     MYSQL_ROOT_PASSWORD: "admin"
  #   volumes: 
  #     - ./backend/.dbdata:/var/lib/mysql
  #     - ./util/init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
  #   ports: 
  #     - 33066:3306
  #   networks: 
  #     - fullstack 

networks: 
  fullstack:
    driver: bridge


    
    